<?php

/**
 * PluginContact
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    pixToolsPlugin
 * @subpackage plugin
 * @author     Nicolas Ricci <nr@agencepix.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginContact extends BaseContact
{
    static public $personType = array(
      'Mme' => 'label_contact_option_mme',
      'Mlle' => 'label_contact_option_mlle',
      'Mr' => 'label_contact_option_mr'
    );

    public function getFullName(){
        return $this->getFirstname().' '.$this->getLastname();
    }
}