<?php

/**
 * PluginNewsletterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginNewsletterTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginNewsletterTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginNewsletter');
    }
}