Contact:
  actAs:
    Timestampable:

  columns:
    title: { type: string(50), notnull: true }
    lastname: { type: string(255), notnull: true }
    firstname: { type: string(255), notnull: false }
    phone: { type: string(255), notnull: true }
    email: { type: string(255), notnull: true }
    company: { type: string(255), notnull: false }
    address: { type: string(255), notnull: false }
    postcode: { type: string(50), notnull: true }
    city: { type: string(255), notnull: true }
    country: { type: string(255), notnull: true }
    comments: clob
    referer: clob
    host: varchar(255)
    keywords: varchar(255)

  options:
    collate: utf8_unicode_ci
    charset: utf8

Newsletter:
  columns:
    email: varchar(255)
    is_confirmed: {type: boolean, default: false}
    referer: clob
    host: varchar(255)
    keywords: varchar(255)

  actAs:
    Timestampable:

  options:
    collate: utf8_unicode_ci
    charset: utf8