Contact:
  actAs:
    Timestampable:

  columns:
    lastname: string(255)
    firstname: string(255)
    phone: string(50)
    email: string(255)
    subject: string(255)
    comments: clob
    referer: clob
    host: varchar(255)
    keywords: varchar(255)

  options:
    collate: utf8_unicode_ci
    charset: utf8

Newsletter:
  columns:
    email: varchar(255)
    is_confirmed: {type: boolean, default: false}
    referer: clob
    host: varchar(255)
    keywords: varchar(255)

  actAs:
    Timestampable:

  options:
    collate: utf8_unicode_ci
    charset: utf8